0.4.2

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -6,7 +6,7 @@ steps:
         echo "Found [deploy] tag. Proceeding..."
       else
         echo "No [deploy] tag found. Skipping build."
-        exit 0 # Use exit 1 if you want the build to show as 'Failed'
+        exit 1 # Use exit 1 if you want the build to show as 'Failed'
       fi
   # 1. Build the container image
   # We always build to ensure the code is valid/testable
